apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-sync
  data:
  - secretKey: foobar
    remoteRef:
      key: secret/foo
      property: my-value
kubectl apply -f eso-external-secret.yml
kubectl get ExternalSecret my-cool-secret
kubectl get ExternalSecret my-cool-secret -o yaml


vault login hvs.hsVNNWHGrqyhRJ7KIiQVe5yL && vault kv get my-cool-secret

  popd
}

function init_vault() {
  pushd vault
  helm repo add hashicorp https://helm.releases.hashicorp.com
  helm repo update
  cat > helm-vault-raft-values.yml <<EOF
server:
  affinity: ""
  ha:
    enabled: true
    raft: 
      enabled: true
